import type { Metadata } from "next";

import { aloevera, helvetica } from "@/assets/fonts";
import { Navbar } from "@/components/layout/navbar";
import { cn } from "@/lib/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          helvetica.className,
          aloevera.variable,
          "bg-foreground text-background relative antialiased"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
